Fix typo preventing `omnibus-ctl int <program>` from working
Attempting to use the `int` command would result in this:

```
/opt/gitlab/embedded/lib/ruby/gems/2.3.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:730:in `run': undefined method `int' for #<Omnibus::Ctl:0x0000000132dec0> (NoMethodError)
        from /opt/gitlab/embedded/lib/ruby/gems/2.3.0/gems/omnibus-ctl-0.5.0/bin/omnibus-ctl:31:in `<top (required)>'
        from /opt/gitlab/embedded/bin/omnibus-ctl:22:in `load'
        from /opt/gitlab/embedded/bin/omnibus-ctl:22:in `<main>'
```

Signed-off-by: Stan Hu <stanhu@gmail.com>